- name: Install utilities
  become: true
  apt:
    name:
      - npm
      - bat
      - neofetch
      - python3
    state: latest
  tags: ['utilities']

- name: Install http-prompt with pip
  pip:
    name: http-prompt
  tags: ['utilities']