- name: Install utilities
  become: true
  apt:
    name:
      - npm
      - bat
      - neofetch
    state: latest
  tags: ['utilities']

- name: Install http-prompt with pip
  pip:
    name: http-prompt
    virtualenv: /opt/venv
  tags: ['utilities']