- name: Install dependencies
  become: true
  apt:
    name:
      - 'zsh'
    state: latest
  tags: ['zsh']

- name: Download Oh My Zsh installer
  get_url: 
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-install.sh
    mode: 0755
  tags: ['zsh']

- name: Install Oh My Zsh
  ignore_errors: true
  become: true
  expect:
    command: /tmp/zsh-install.sh --skip-chsh
    responses:
      "{{ oh_my_zsh_responses }}"
  no_log: true
  tags: ['zsh']

- name: Clone Oh My Zsh plugins
  git:
    repo: "https://github.com/{{ item.project_user }}/{{ item.project_name }}"
    dest: "/root/.oh-my-zsh/custom/{{ item.type }}/{{ item.project_name }}"
  with_items: "{{ oh_my_zsh_plugins }}"

- name: Get theme project name
  set_fact:
    theme_project_name: "{{ oh_my_zsh_plugins | selectattr('type', 'equalto', 'themes') | map(attribute='project_name') | first }}"
  tags: ['zsh']

- name: Print theme project name with duplication
  debug:
    msg: "{{ theme_project_name }}/{{ theme_project_name }}"
  tags: ['zsh']

- name: Set zsh theme in ~/.zshrc
  lineinfile:
    path: /root/.zshrc
    regexp: '^ZSH_THEME='
    line: 'ZSH_THEME="{{ theme_project_name }}/{{ theme_project_name }}"'

- name: Set zsh plugins in ~/.zshrc
  lineinfile:
    path: /root/.zshrc
    regexp: '^plugins='
    line: "plugins=(git {{ oh_my_zsh_plugins | selectattr('type', 'equalto', 'plugins') | map(attribute='project_name') | join(' ') }})"

- name: Remind user to switch to zsh
  debug:
    msg: "To use zsh, please run the command 'zsh' or start a new session."
  tags: ['zsh']

- name: Copy .zshrc to user home directory
  copy:
    src: "/root/.zshrc"
    dest: "/home/{{ user }}/"
  become: true
  become_user: root
  tags: ['zsh']

- name: Copy .oh-my-zsh to user home directory
  copy:
    src: "/root/.oh-my-zsh"
    dest: "/home/{{ user }}/"
  become: true
  become_user: root
  tags: ['zsh']

- name: Copy .profile to user home directory
  copy:
    src: "/root/.profile"
    dest: "/home/{{ user }}/"
  become: true
  become_user: root
  tags: ['zsh']

- name: Change ownership of files for my-user
  become_user: root
  file:
    path: /home/{{ user }}/{{ item }}
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - .zshrc
    - .oh-my-zsh
    - .profile
  tags: ['zsh']

- name: Change default shell to zsh for user
  become: true
  user:
    name: "{{ user }}"
    shell: /bin/zsh
  tags: ['zsh']

