- name: Create directory for Kubernetes keyring
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Add Kubernetes APT key
  shell: "curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg -o /etc/apt/keyrings/kubernetes.asc"
  args:
    creates: /etc/apt/keyrings/kubernetes.asc
  become: true

- name: Add Kubernetes APT repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/kubernetes.asc] https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  tags: ['kubeadm']

- name: Install Kubernetes
  become: true
  apt:
    name:
      - kubeadm
      - kubelet
      - kubectl
    state: present
  tags: ['kubeadm']

- name: Check if Kubernetes is installed
  command: kubectl version --client
  ignore_errors: true
  register: kubectl_version
  tags: ['kubeadm']

- name: Stop playbook if Kubernetes is not installed
  fail:
    msg: "Kubernetes is not installed."
  when: "'Client Version' not in kubectl_version.stdout"
  tags: ['kubeadm']