- name: Add proxy parameter to ~/.profile
  lineinfile:
    path: "/home/{{ user }}/.profile"
    line: |
      export https_proxy={{ proxy_parameters.https_proxy }}
      export HTTPS_PROXY=${https_proxy}
      export http_proxy={{ proxy_parameters.http_proxy }}
      export HTTP_PROXY=${http_proxy}
      export no_proxy="{{ proxy_parameters.no_proxy }}"
    create: yes
    state: present
    insertafter: EOF
  tags: ['proxy-settings']

- name: Add proxy parameter to /etc/apt/apt.conf
  become: true
  lineinfile:
    path: "/etc/apt/apt.conf"
    line: |
      Acquire::http::Proxy "{{ proxy_parameters.http_proxy }}";
      Acquire::https::Proxy "{{ proxy_parameters.https_proxy }}";
    state: present
    insertafter: EOF
  tags: ['proxy-settings']

- name: Add proxy parameter to ~/.gitconfig
  lineinfile:
    path: "/home/{{ user }}/.gitconfig"
    line: |
      [url "https://"]
      insteadOf = git://
      [credential]
      helper = store
      [https]
      proxy = {{ proxy_parameters.https_proxy }}
      [http]
      proxy = {{ proxy_parameters.http_proxy }}
    create: yes
    state: present
    insertafter: EOF
  tags: ['proxy-settings']

- name: Add proxy parameter to ~/.gitconfig
  lineinfile:
    path: "/home/{{ user }}/.gitconfig"
    line: |
      [url "https://"]
      insteadOf = git://
      [credential]
      helper = store
      [https]
      proxy = {{ proxy_parameters.https_proxy }}
      [http]
      proxy = {{ proxy_parameters.http_proxy }}
    create: yes
    state: present
    insertafter: EOF
  tags: ['proxy-settings']