- name: Global Playbook
  hosts: host
  become: true
  environment:
    http_proxy: "{{ proxy_parameters.http_proxy }}"
    https_proxy: "{{ proxy_parameters.https_proxy }}"
    no_proxy: "{{ proxy_parameters.no_proxy }}"
  roles:
    - name: user
      when: create_user

    - name: proxy
      when: proxy_parameters.use_proxy

    - name: wsl_conf

    - name: dependencies

    - name: utilities

    - name: docker

    - name: k3s
      when: use_k3s

    - name: kubeadm
      when: not use_k3s

    - name: helm

    - name: k9s

    - name: zsh
      when: install_zsh

    - name: k3s-scripts
      when: use_k3s
